data/other/enna.desktop: Comply with Desktop Entry Specification (patch by Paul Menzel <paulepanter at users.sourceforge.net>)
Building Enna using OpenEmbedded gave the following warnings.

    ERROR: QA Issue with enna: /oe/angstrom-dev/work/armv7a-angstrom-linux-gnueabi/enna-0.4.0+hg-r1.0/packages-split/enna/usr/share/applications/enna.desktop: error: value "ENLIGHTENMENT;Application;AudioVideo;Player;" for key "Categories" in group "Desktop Entry" contains an unregistered value "ENLIGHTENMENT"; values extending the format should start with "X-"
    ERROR: QA Issue with enna: /oe/angstrom-dev/work/armv7a-angstrom-linux-gnueabi/enna-0.4.0+hg-r1.0/packages-split/enna/usr/share/applications/enna.desktop: warning: value "ENLIGHTENMENT;Application;AudioVideo;Player;" for key "Categories" in group "Desktop Entry" contains a deprecated value "Application"

Fix those issues according to the latest Desktop Entry Specification [1]. Deprecated items are listed in Appendix C [2]. The values for `Categories` [3] are listed in the Desktop Menu Specification [4] and `ENLIGHTENMENT` is not a registered category [5] and therefore »must be prefixed by the string "X-" indicating that they are extensions« [6].

[1] http://standards.freedesktop.org/desktop-entry-spec/latest/
[2] http://standards.freedesktop.org/desktop-entry-spec/latest/apc.html
[3] http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html
[4] http://www.freedesktop.org/wiki/Specifications/menu-spec
[5] http://standards.freedesktop.org/menu-spec/latest/apa.html
[6] http://standards.freedesktop.org/menu-spec/latest/ar01s03.html